### PR TITLE
fix(bottom-dock-and-action-toolbar): remove bottom dock and toolbar

### LINKED ISSUE #122: Removal of bottom dock and top buttons from snapshot image
### Current Behavior

Currently the screenshots presented by the extension have a dock at the bottom and some buttons at the top.
image

### Desired Behavior

Removal of these components will help in increasing the amount of space available to view the content.
Moreover, it will further remove obstructions overlapping with the design presented.

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by jerensl**
**Description**
Fixes #122 

some ID is still not available on the playground, wait until the next release before merging this PR

Also, we need this got merged before the next cycle release:
- [x] https://github.com/meshery/meshery/pull/12127 (Not in Playground yet)
- [x] https://github.com/layer5labs/meshery-extensions/pull/2898
- [x] https://github.com/layer5labs/meshery-extensions/pull/2891

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: cypress-action/cypress/e2e/e2e/loadDesign.js [hunk 1]
```diff
@@ -64,12 +64,19 @@ const captureSnapshot = ({ window, designId, theme }) => {
 
 const removeWidgets = () => {
     const classes = ["MuiToolbar-root", "MuiDrawer-paperAnchorDockedLeft", "MuiSpeedDial-root"] ;
```
Comment (aabidsofi19) [inline cypress-action/cypress/e2e/e2e/loadDesign.js:66]: @jerensl  lets replace these with dedicated ids so we dont accidenlty remove important elements .

**Review by aabidsofi19 — CHANGES_REQUESTED** [review]
